#+title: Content
#+HUGO_BASE_DIR: ./
#+AUTHOR: Steve Tautonico


* TODO My First Experience Developing for the Flipper Zero
:properties:
:export_file_name: my-first-experience-developing-for-the-flipper-zero
:export_description: Description goes here
:export_date: 2022-08-07
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :unlisted true
:end:

** Preface
For those who don't know, the [[https://flipperzero.one/][Flipper Zero]] is a little open source multi-tool
device that is able to read/write/emulate several wireless protocols such as RFID, NFC, the sub-GHz frequency
range, IR, and more. Since the flipper's firmware is open source, many developers in the community are currently
expanding the official firmware with additional functionality by adding additional plugins and reworking existing features.
One of these default features is the ability to act as a U2F key (over USB). My current U2F device is an (/unspecified/)
hardware U2F and TOTP key combo. I wanted a backup just in case I lost my /unspecified/ hardware key. Using the Flipper
(will be referred to as *f0* for the rest of this article) as a U2F key seemed like a decent idea since it was a default feature.
However, it does not support TOTP by default. The f0 does have a RTC (real-time clock) chip on board, meaning it could
theoretically support a TOTP app. Since the f0 is open source, I decided to try to write it myself.
Note: I will only be discussing my experiences specifically related to the f0. Any issues I had due to my lack of knowledge of C will be left out.

** Research
Before programming anything, I needed to do some research in order to find out how to even begin programming an app for the f0.
I quickly discovered that no official documentation is available, which made getting started really difficult. I tried asking
the wonderful people of the [[http://flipperzero.one/discord][discord]] where to start. The most common piece of advice I got
was to take a look at other people's apps and see how they were built. Looking around some firmware forks, I came across a simple
[[https://gist.github.com/CompaqDisc/4e329c501bd03c1e801849b81f48ea61][clock app]] in the [[https://github.com/Eng1n33r/flipperzero-firmware][Unleashed firmware]].
Another resource I was pointed to was [[https://flipper.atmanos.com/docs/overview/intro][Atmanos' Flipper Software Docs]]. This
resource ended up being the most useful overall.

The f0's firmware supports three different GUI paradigms:

1. "/ViewPort/": Simple and very flexible, but no navigation helpers or default components, good for games/graphics applications due to full control of graphics
2. "/ViewDispatcher and View/": Slightly more complex than /ViewPort/, but has the ability to use reusable views and navigation helpers (the one I ended up choosing)
3. "/Scenes and Views/": The most complex and heavy, but ideal for complex apps.

After doing a bit of research, I felt confident in my knowledge and began to program...

** Prototyping
Building a TOTP app for the f0 required two main components: the GUI interface and the TOTP implementation in the backend.

Before I started, I asked the discord to see if anyone has already implemented TOTP. I was told that [[https://github.com/Astrrra][Astra]] had already
built a little [[https://github.com/wetox-team/flipperzero-firmware/tree/gen-totp/applications/totp][TOTP demo]].
Now that I knew the complex part of the project was done, all I needed to do was build a simple interface for this implementation.
Little did I know that I would re-write the app three times over.

During my first attempt, I started programming using the "/ViewPort/" GUI paradigm. This attempt ended quickly when I realized that I was
unable to use the list of items, called the =VariableItemList= or the =Submenu= component (they slightly vary in behavior)

During my second attempt, I tried using the "/Scenes and Views/" GUI paradigm. This paradigm was incredibly hard to wrap my head around.
After a few hours of playing around with some code, I was able to get a simple demo working, but my code was polluted with random
code from the prototyping process. At this point, I realized that this paradigm was way too complex for my needs.

I went into my third attempt with a pretty decent understanding of how the first two paradigms work.
From my understanding, the "/ViewDispatcher and View/" system has two main components: the view dispatcher and the views
(if this wasn't already obvious from the name.) Views can be thought about like pages on a website. The views are similar to
the setup in the "/ViewPort/" paradigm, except for the required =alloc= and =free= method. These views are registered with the
view dispatcher component. This component is in charge of changing which view is currently on the screen. When the view dispatcher
is instructed to set the current view, it calls the view's =alloc= function which allocates memory for the required components of the view
(the view itself and the view model (similar to the view's state)), sets the context passed to the view, and sets up the callbacks for input,
drawing, and more. Once the view dispatcher changes views, it calls the current view's =free= function, which is in charge of freeing any
allocated memory in the view.

I started programming, vaguely following along with the official flipper firmware [[https://github.com/flipperdevices/flipperzero-firmware/tree/dev/applications/debug_tools/display_test][display test program]]
(as suggested by Atmanos's Docs) and was making good progress. The hardest of developing for the flipper seems to be trying to understand
how all the components work together and just how apps are structured in general. Once you understand that, building a flipper app is relatively easy.
Some official documentation on how this all worked would make getting started significantly easier (*wink wink, flipper team 😉*)

# TODO!

** Sources
- [[https://flipper.atmanos.com/][Atmanos' Flipper Software Docs]]
